/*
 * This source file was generated by the Gradle 'init' task
 */
package com.reviewer;

import com.github.javaparser.ast.CompilationUnit;

public class Main {
    public static void main(String[] args) {
        try {
            run(args);
        } catch (Exception e) {
            System.err.println(e.getMessage());
            System.exit(1);
        }
    }

    public static void run(String[] args) {
        if (args.length != 1) {
            throw new IllegalArgumentException("Usage: java -jar MLCodeReviewer.jar <path-to-java-file>");
        }

        String filePath = args[0];
        try {
            CompilationUnit cu = ASTParser.parseFile(filePath);
            if (cu != null) {
                CodeAnalyzer analyzer = new CodeAnalyzer();
                analyzer.analyze(cu);
            } else {
                throw new RuntimeException("Failed to parse the Java file.");
            }
        } catch (Exception e) {
            throw new RuntimeException("Error processing the file: " + filePath, e);
        }
    }
}
