/*
 * This source file was generated by the Gradle 'init' task
 */
package com.reviewer;

import com.github.javaparser.ast.CompilationUnit;

public class Main {
    public static void main(String[] args) {
        if (args.length != 1) {
            System.err.println("Usage: java -jar MLCodeReviewer.jar <path-to-java-file>");
            System.exit(1);
        }

        String filePath = args[0];
        try {
            CompilationUnit cu = ASTParser.parseFile(filePath);
            if (cu != null) {
                CodeAnalyzer analyzer = new CodeAnalyzer();
                analyzer.analyze(cu);
            } else {
                System.err.println("Failed to parse the Java file.");
            }
        } catch (Exception e) {
            System.err.println("Error parsing file: " + e.getMessage());
        }
    }

    public static String getGreeting() {
        return "Hello, Code Reviewer!";
    }
}
