/*
 * This source file was generated by the Gradle 'init' task
 */
package com.reviewer;

public class Main {
    public static void main(String[] args) {
        System.out.println(getGreeting());

        try {
            ASTParser.parseFile("data/SampleCode.java");
        } catch (Exception e) {
            System.err.println("Error parsing file: " + e.getMessage());
        }
    }

    public static String getGreeting() {
        return "Hello, Code Reviewer!";
    }
}
