name: Code Review

on:
  pull_request:
    paths:
      - '**/*.java'

jobs:
  review:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Build project
        run: ./gradlew build

      - name: Run code analyzer
        run: |
          for file in $(git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep '\.java$'); do
            java -jar app/build/libs/MLCodeReviewer.jar $file
          done

      - name: Comment on PR
        uses: actions/github-script@v4
        with:
          script: |
            const fs = require('fs');
            const files = fs.readdirSync('app/build/libs');
            const results = files.filter(file => file.endsWith('.log')).map(file => fs.readFileSync(`app/build/libs/${file}`, 'utf8')).join('\n');
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: results || 'No issues found.'
            });
